# SPDX-FileCopyrightText: 2023 Justin Hammond <justin@dynam.ac>
#
# SPDX-License-Identifier: MIT

DESCRIPTION = "The Oxygen Sound Theme"
SUMMARY = "The Oxygen Sound Theme"
HOMEPAGE = "https://invent.kde.org/plasma/oxygen-sounds"
LICENSE = " BSD-2-Clause & CC-BY-3.0 & CC0-1.0 & LGPL-3.0-or-later"


inherit cmake_plasma
inherit reuse_license_checksums


DEPENDS = " \
"


KF5_REUSE_LICENSECHECK_ENABLED="1"

